---
swagger: "2.0"
info:
  description: >-
    Tenant to agreement resolver. This service gives the possibility to get the
    agreement of a tenant given
    <div class="postman-run-button"
    data-postman-action="collection/import"
    data-postman-var-1="29355b09bb2db8526bab"
    data-postman-param="env%5Bproduction%5D=W3sia2V5Ijoic3VwZXJ2aXNvci5vYWkuaG9zdCIsInZhbHVlIjoic3VwZXJ2aXNvci5vYWkuZ292ZXJuaWZ5LmlvIiwidHlwZSI6InRleHQiLCJlbmFibGVkIjp0cnVlLCJob3ZlcmVkIjpmYWxzZX0seyJrZXkiOiJtb25pdG9yLm9haS5ob3N0IiwidmFsdWUiOiJtb25pdG9yLm9haS5nb3Zlcm5pZnkuaW8iLCJ0eXBlIjoidGV4dCIsImVuYWJsZWQiOnRydWUsImhvdmVyZWQiOmZhbHNlfSx7ImtleSI6InN1cGVydmlzb3IuaG9zdCIsInZhbHVlIjoic3VwZXJ2aXNvci5nb3Zlcm5pZnkuaW8iLCJ0eXBlIjoidGV4dCIsImVuYWJsZWQiOnRydWV9XQ=="></div>
    <script type="text/javascript">
      (function (p,o,s,t,m,a,n) {
        !p[s] && (p[s] = function () { (p[t] || (p[t] = [])).push(arguments); });
        !o.getElementById(s+t) && o.getElementsByTagName("head")[0].appendChild((
          (n = o.createElement("script")),
          (n.id = s+t), (n.async = 1), (n.src = m), n
        ));
      }(window, document, "_pm", "PostmanRunObject", "https://run.pstmn.io/button.js"));
    </script>
  version: "1.0.0"
  title: "Tenants"
  termsOfService: "http://tenants.governify.io/terms/"
  contact:
    name: "ISA Group"
    url: "http://governify.io"
    email: "isagroup.us@gmail.com"
  license:
    name: Apache License 2.0
    url: "http://www.apache.org/licenses/"
basePath: "/api/v1"
schemes:
- http
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /tenants:
    post:
      tags:
      - tenants
      description: This endpoint creates a new tenant information.
      operationId: tenantsPOST
      parameters:
        - name: tenant
          in: body
          description: Tenant that will be created
          required: true
          schema:
            $ref: '#/definitions/newTenant'
      responses:
        200:
          description: Tenant has been created.
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/errorModel"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/errorModel"
        default:
          description: "Unexpected error"
      x-swagger-router-controller: "Tenants"
    get:
      tags:
      - "tenants"
      description: >-
        This endpoint returns the tenant information that is required. You must
        pass keyName and keyValue and the system returns a specific tenant
        filtered by this keyName with this keyValue.
      operationId: "tenantsGET"
      parameters:
      - name: "keyName"
        in: "query"
        description: "Name of query param"
        required: false
        type: "string"
      - name: "keyValue"
        in: "query"
        description: "Value of query param"
        required: false
        type: "string"
      responses:
        200:
          description: "Scope information that is required"
          schema:
            $ref: "#/definitions/tenant"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/errorModel"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/errorModel"
        default:
          description: "Unexpected error"
      x-swagger-router-controller: "Tenants"
  /tenants/{id}:
    delete:
      tags:
      - "tenants"
      description: Delete tenant with tenantId = {id}
      operationId: "tenantsIdDELETE"
      parameters:
      - name: id
        in: path
        description: "Tenant identifier"
        required: true
        type: "string"
      responses:
        200:
          description: Tenant with {id} has been deleted
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/errorModel"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/errorModel"
        default:
          description: "Unexpected error"
      x-swagger-router-controller: "Tenants"
    put:
      tags:
      - "tenants"
      description: Update tenant with tenantId = {id}
      operationId: "tenantsIdPUT"
      parameters:
      - name: id
        in: path
        description: "Tenant identifier"
        required: true
        type: "string"
      - name: tenant
        in: body
        description: "Tenant updates"
        required: true
        schema:
          $ref: '#/definitions/newTenant'
      responses:
        200:
          description: Tenant with {id} has been update
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/errorModel"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/errorModel"
        default:
          description: "Unexpected error"
      x-swagger-router-controller: "Tenants"
definitions:
  tenant:
    type: "object"
    properties:
      _id:
        type: string
      agreement:
        type: "string"
      scope:
        type: object
        properties: {}

  newTenant:
    type: object
    properties:
      agreement:
        type: string
      scope:
        type: object
        properties: {}

  namespace:
    type: object
    properties:
      _id:
        type: string
      name:
        type: string
      description:
        type: string

  newNamespace:
    type: object
    properties:
      name:
        type: string
      description:
        type: string

  errorModel:
    type: "object"
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
