---
production:
  services:
    db:
      uri: "mongodb://mongo:27017/tenants"
  port: 80
  logger: 'debug'
development:
  services:
    db:
      uri: "mongodb://localhost:27017/tenants"
  port: 5031
  logger: 'debug'
